nodes:
  node1: node1
  node2: node2
  node3: node3
  node4: node4
  node5: node5
  node6: node6
  node7: node7
  node8: node8
  node9: node9
  node10: node10

edges:
  - [START, node1]                          
  - [node1, node2]                          
  - [node2, node3]                          
  - [node2, node4]                          
  - [node3, node5]                          
  - [node4, node5]                          
  - [node6, END]                            
  - [node7, node8]                          
  - [node7, node9]                          
  - [node8, node10]                         
  - [node9, node10]                         
  - [node10, END]                          

conditional_edges:
  - source: node5                               
    condition_fn: routing_function
    mapping:
      return_docs: node6                        
      generate_answer: node7                    